name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
  integration:
    if: github.event.label.name == 'integration'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Install dependencies
        run: |
          yarn
          yarn link

      - name: Build
        run: yarn build

      - name: Integration
        run: ./scripts/integration.sh
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
