name: Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Integration
        run: ./scripts/integration.sh
        env:
          FOO_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
